import bpy

for x in bpy.context.object.data.bones:
	x.name = x.name.replace('全ての親','root')
	x.name = x.name.replace('.R','_r')
	x.name = x.name.replace('.L','_l')
	x.name = x.name.replace('足ＩＫ','ik_foot')
	x.name = x.name.replace('足首先','ball')
	x.name = x.name.replace('足首','foot')
	x.name = x.name.replace('足','thigh')
	x.name = x.name.replace('センター','spine_01')
	x.name = x.name.replace('下半身','pelvis')
	x.name = x.name.replace('ひざ','calf')
	x.name = x.name.replace('上半身２','spine_03')
	x.name = x.name.replace('上半身','spine_02')
	x.name = x.name.replace('肩','clavicle')
	x.name = x.name.replace('腕捩','upperarm_twist_01')
	x.name = x.name.replace('腕','upperarm')
	x.name = x.name.replace('ひじ','lowerarm')
	x.name = x.name.replace('手捩','lowerarm_twist_01')
	x.name = x.name.replace('手首','hand')
	x.name = x.name.replace('親指０','thumb_01')
	x.name = x.name.replace('親指１','thumb_02')
	x.name = x.name.replace('親指２','thumb_03')
	x.name = x.name.replace('小指１','pinky_01')
	x.name = x.name.replace('小指２','pinky_02')
	x.name = x.name.replace('小指３','pinky_03')
	x.name = x.name.replace('薬指１','ring_01')
	x.name = x.name.replace('薬指２','ring_02')
	x.name = x.name.replace('薬指３','ring_03')
	x.name = x.name.replace('中指１','middle_01')
	x.name = x.name.replace('中指２','middle_02')
	x.name = x.name.replace('中指３','middle_03')
	x.name = x.name.replace('人指１','index_01')
	x.name = x.name.replace('人指２','index_02')
	x.name = x.name.replace('人指３','index_03')
	x.name = x.name.replace('首','neck_01')
	x.name = x.name.replace('頭','head')
